/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abu_andtest_JNIUtil */

#ifndef _Included_com_abu_andtest_JNIUtil
#define _Included_com_abu_andtest_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_abu_andtest_JNIUtil
 * Method:    getWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_abu_andtest_JNIUtil_getWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
