/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abu_andtest_JNI02 */

#ifndef _Included_com_abu_andtest_JNI02
#define _Included_com_abu_andtest_JNI02
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_abu_andtest_JNI02
 * Method:    getWorldxxxx
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_abu_andtest_JNI02_getWorldxxxx
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
